name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
        with:
          node-version: "16"
      - run: npm install
